### PR TITLE
fix(dubbo): fix incorrect values for localhost and localport at server span tag

### LINKED ISSUE #357: DubboSofaTracerFilter Server span tag value error
## code error 

The method `appendRpcServerSpanTags` in class  `DubboSofaTracerFilter` has incorrect values for localhost and local port.

```java
384 tagsStr.put(CommonSpanTags.LOCAL_HOST, rpcContext.getRemoteHost());
385 tagsStr.put(CommonSpanTags.LOCAL_PORT, String.valueOf(rpcContext.getRemotePort()));
```

### PR DESCRIPTION
**Pull request by zmapleshine**
#127 # Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

```
Cause code error
```

### Modification:

Describe the idea and modifications you've done.
```
Fix incorrect localhost local port values at server span tags
```

### Result:

Fixes #357.

### CODE REVIEW

**Comment by glmapper** [comment]
@zmapleshine you should provide some test case for this PR

**Review by glmapper — APPROVED** [review]
LGTM

**Comment by glmapper** [comment]
@zmapleshine master 是 2.x 版本，目前不在继续维护；可以提到 3.x 分支

**Comment by zmapleshine** [comment]
@glmapper see pr #386

**Comment by glmapper** [comment]
merge to 3.x.  https://github.com/sofastack/sofa-tracer/pull/386

**Pull request closed without merging**
