### PR TITLE
Restore parent span for redis plugin

### LINKED ISSUE #463: Redis plugin未恢复paren span,导致span id的层级无限增长
### Describe the bug
链路中每执行一次redis操作，span id就会向下增长一层。
此时日志输出如下所示：
[0.1] 接受到请求
[0.1.1] 执行业务处理1
[0.1.2] 执行redis处理1
[0.1.2.1] 执行业务处理2
[0.1.2.2] 执行redis处理2
[0.1.2.2.1] 执行业务处理3
...

### Expected behavior
redis plugin 在redis操作结束，记录span日志、上报span后，将parent span恢复到当前栈（SofaTraceContext）
此时日志输出如下所示：
[0.1] 接受到请求
[0.1.1] 执行业务处理1
[0.1.2] 执行redis处理1
[0.1.3] 执行业务处理2
[0.1.4] 执行redis处理2
[0.1.5] 执行业务处理3
...

### Actual behavior
redis plugin 在redis操作结束，记录span日志、上报span（clientReceiveTagFinish）后，没有将parent span恢复到当前栈（SofaTraceContext），导致span id的层级会无限增长下去。

### Environment

- SOFATracer version: 3.1.1
- JVM version (e.g. `java -version`):  1.8.0_301
- OS version (e.g. `uname -a`): macOS 11.4
- Maven version: 3.5.4
- IDE version: IntelliJ IDEA 2021.2 (Ultimate Edition)

### PR DESCRIPTION
**Pull request by it-linnan**
### Motivation:

解决redis plugin未恢复paren span,导致span id的层级无限增长的问题

### Modification:

Describe the idea and modifications you've done.

在finish span后，将parent span恢复到当前栈中

### Result:

Fixes #463.

### CODE REVIEW

**Comment by glmapper** [comment]
@it-linnan provide test case for changes

**Comment by glmapper** [comment]
@it-linnan pls provide test case for this PR

**Comment by it-linnan** [comment]
> @it-linnan pls provide test case for this PR

OK

**Review by glmapper — APPROVED** [review]
LGTM

**Comment by glmapper** [comment]
@it-linnan check format fails, pls exec 'mvn clean compile' in local and re-submit

**Comment by glmapper** [comment]
use this PR commit https://github.com/sofastack/sofa-tracer/pull/496

**Pull request closed without merging**
