### PR TITLE
Added shadowtest support

### PR DESCRIPTION
**Pull request by ericmoshare**
### Motivation:

     -Added operationName  adapter, in order to resolve operationName get displayed as unknown issue.
     -Added stressTest mark support.

### Modification:
     -Resolve operationName, traceId  during sending the request to Zipkin.

### Result:

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Review by xzchaoo — APPROVED** [review]
LGTM

**Comment by glmapper** [comment]
@nobodyiam @xzchaoo why not merge this PR?

**Comment by nobodyiam** [comment]
@glmapper would you please help to review this pr?

**Comment by glmapper** [comment]
@ericmoshare PLS check format 
image
you can exec 'mvn clean compile'  in local to format your code

**Pull request closed without merging**
