### PR TITLE
Fixes gh-367.

### PR DESCRIPTION
**Pull request by chenmudu**
### Motivation:

Support rabbit mq in SOFATracer 3.1.X。

### Modification:

Support rabbit mq in SOFATracer 3.1.X。

### Result:

Fixes #gh-367

add rabbit mq plugin for SOFATracer 3.1.X。

### CODE REVIEW

**Comment by chenmudu** [comment]
The reason for this PR comes from personal misoperation. I mistakenly deleted the source warehouse code. I‘m so sorry about this.

**Review by glmapper — APPROVED** [review]
LGTM

**Comment by glmapper** [comment]
@chenmudu when merging the Kafka plugin, there has got conflicts

**Comment by chenmudu** [comment]
> @chenmudu when merging the Kafka plugin, there has got conflicts

because r

**Comment by chenmudu** [comment]
> @chenmudu when merging the Kafka plugin, there has got conflicts

hi, it's rabbit plugin, because the kafka plugin was merged into the 3.x branch before the rabbit plugin. this is a safe merge  operation. thx !

**Pull request merged**
