### PR TITLE
Leave SofaTraceContext to spring ioc management

### PR DESCRIPTION
**Pull request by zhongxiongzeng**
### Motivation:

Explain the context, and why you're making that change.
To make others understand what is the problem you're trying to solve.

### Modification:

Describe the idea and modifications you've done.

### Result:

Fixes #<GitHub issue number>. 

If there is no issue then describe the changes introduced by this PR.

### CODE REVIEW

**Comment by zhongxiongzeng** [comment]
I have signed cla

**Comment by glmapper** [comment]
is there an issue to describe this PR?  I think SofaTraceContext cannot be Managed to spring IOC.

**Comment by zhongxiongzeng** [comment]
When I need to get Span ID，i must do this :`SofaTraceContextHolder.getSofaTraceContext().getCurrentSpan().getSofaTracerSpanContext().getSpanId();`
it's to long and not graceful, i wanna inject SofaTraceContext by @Resource/@Autowired,like inject request by @Autowired

**Comment by glmapper** [comment]
> When I need to get Span ID，i must do this :`SofaTraceContextHolder.getSofaTraceContext().getCurrentSpan().getSofaTracerSpanContext().getSpanId();`
> it's to long and not graceful, i wanna inject SofaTraceContext by @Resource/@Autowired,like inject request by @Autowired

If there is no use the spring, how to do？

**Pull request closed without merging**
